/**
 * Airport codes with city names and domestic/international flag.
 * Used for display and for trip route type (domestic vs international).
 */

interface AirportInfo {
  city: string;
  isDomestic: boolean;
}

const AIRPORTS: Record<string, AirportInfo> = {
  ABT: { city: "Al Baha", isDomestic: true },
  AHB: { city: "Abha", isDomestic: true },
  AJF: { city: "Jouf", isDomestic: true },
  BHH: { city: "Bisha", isDomestic: true },
  DMM: { city: "Dammam", isDomestic: true },
  DWD: { city: "Dawadmi", isDomestic: true },
  EAM: { city: "Najran", isDomestic: true },
  ELQ: { city: "Gassim", isDomestic: true },
  GIZ: { city: "Jazan", isDomestic: true },
  HAS: { city: "Hail", isDomestic: true },
  JED: { city: "Jeddah", isDomestic: true },
  MED: { city: "Madinah", isDomestic: true },
  NUM: { city: "Neom", isDomestic: true },
  RAE: { city: "Arar", isDomestic: true },
  RAH: { city: "Rafha", isDomestic: true },
  RSI: { city: "Red Sea International", isDomestic: true },
  RUH: { city: "Riyadh", isDomestic: true },
  SHW: { city: "Sharurah", isDomestic: true },
  TUU: { city: "Tabuk", isDomestic: true },
  ULH: { city: "AlUla", isDomestic: true },
  URY: { city: "Gurayat", isDomestic: true },
  WAE: { city: "Wadi Al Dawasir", isDomestic: true },
  YNB: { city: "Yanbu", isDomestic: true },
  ABV: { city: "Abuja", isDomestic: false },
  ADD: { city: "Addis Ababa", isDomestic: false },
  ALG: { city: "Algiers", isDomestic: false },
  AMM: { city: "Amman", isDomestic: false },
  AMS: { city: "Amsterdam", isDomestic: false },
  AQI: { city: "Qaisumah", isDomestic: false },
  AUH: { city: "Abu Dhabi", isDomestic: false },
  BAH: { city: "Manama", isDomestic: false },
  BCN: { city: "Barcelona", isDomestic: false },
  BHX: { city: "Birmingham", isDomestic: false },
  BKK: { city: "Bangkok", isDomestic: false },
  BLR: { city: "Bengaluru", isDomestic: false },
  BOM: { city: "Mumbai", isDomestic: false },
  CAI: { city: "Cairo", isDomestic: false },
  CAN: { city: "Guangzhou", isDomestic: false },
  CDG: { city: "Paris", isDomestic: false },
  CMN: { city: "Casablanca", isDomestic: false },
  COK: { city: "Kochi", isDomestic: false },
  DAC: { city: "Dhaka", isDomestic: false },
  DEL: { city: "New Delhi", isDomestic: false },
  DOH: { city: "Doha", isDomestic: false },
  DPS: { city: "Denpasar", isDomestic: false },
  DXB: { city: "Dubai", isDomestic: false },
  FCO: { city: "Rome", isDomestic: false },
  FRA: { city: "Frankfurt", isDomestic: false },
  GVA: { city: "Geneva", isDomestic: false },
  HBE: { city: "Alexandria", isDomestic: false },
  HYD: { city: "Hyderabad", isDomestic: false },
  IAD: { city: "Washington", isDomestic: false },
  ISB: { city: "Islamabad", isDomestic: false },
  IST: { city: "Istanbul", isDomestic: false },
  JFK: { city: "New York", isDomestic: false },
  KAN: { city: "Kano", isDomestic: false },
  KHI: { city: "Karachi", isDomestic: false },
  KUL: { city: "Kuala Lumpur", isDomestic: false },
  KWI: { city: "Kuwait City", isDomestic: false },
  LGW: { city: "London Gatwick", isDomestic: false },
  LHE: { city: "Lahore", isDomestic: false },
  LHR: { city: "London Heathrow", isDomestic: false },
  LKO: { city: "Lucknow", isDomestic: false },
  LOS: { city: "Lagos", isDomestic: false },
  MAD: { city: "Madrid", isDomestic: false },
  MAN: { city: "Manchester", isDomestic: false },
  MLE: { city: "Malé", isDomestic: false },
  MNL: { city: "Manila", isDomestic: false },
  MRU: { city: "Mauritius", isDomestic: false },
  MUC: { city: "Munich", isDomestic: false },
  MUX: { city: "Multan", isDomestic: false },
  MXP: { city: "Milan Malpensa", isDomestic: false },
  NBO: { city: "Nairobi", isDomestic: false },
  PEW: { city: "Peshawar", isDomestic: false },
  PKX: { city: "Beijing Daxing", isDomestic: false },
  SIN: { city: "Singapore", isDomestic: false },
  SSH: { city: "Sharm El Sheikh", isDomestic: false },
  TUN: { city: "Tunis", isDomestic: false },
  VIE: { city: "Vienna", isDomestic: false },
  YYZ: { city: "Toronto", isDomestic: false },
  AAL: { city: "Aalborg", isDomestic: false },
  AAR: { city: "Aarhus", isDomestic: false },
  AAT: { city: "Altay", isDomestic: false },
  ABE: { city: "Allentown", isDomestic: false },
  ABJ: { city: "Abidjan", isDomestic: false },
  ABR: { city: "Aberdeen", isDomestic: false },
  ABY: { city: "Albany", isDomestic: false },
  ABZ: { city: "Aberdeen", isDomestic: false },
  ACA: { city: "Acapulco", isDomestic: false },
  ACC: { city: "Accra", isDomestic: false },
  ACE: { city: "Lanzarote", isDomestic: false },
  ACX: { city: "Xingyi", isDomestic: false },
  ADA: { city: "Adana", isDomestic: false },
  ADB: { city: "Izmir", isDomestic: false },
  ADF: { city: "Adiyaman", isDomestic: false },
  ADL: { city: "Adelaide", isDomestic: false },
  AEB: { city: "Baise", isDomestic: false },
  AER: { city: "Sochi", isDomestic: false },
  AES: { city: "Alesund", isDomestic: false },
  AEX: { city: "Alexandria", isDomestic: false },
  AFA: { city: "San Rafael", isDomestic: false },
  AGA: { city: "Agadir", isDomestic: false },
  AGH: { city: "Angelholm", isDomestic: false },
  AGP: { city: "Malaga", isDomestic: false },
  AGR: { city: "Agra", isDomestic: false },
  AGU: { city: "Aguascalientes", isDomestic: false },
  AJA: { city: "Ajaccio", isDomestic: false },
  AJI: { city: "Agri", isDomestic: false },
  AKA: { city: "Ankang", isDomestic: false },
  AKL: { city: "Auckland", isDomestic: false },
  AKU: { city: "Aksu", isDomestic: false },
  ALA: { city: "Almaty", isDomestic: false },
  ALC: { city: "Alicante", isDomestic: false },
  ALF: { city: "Alta", isDomestic: false },
  AMD: { city: "Ahmedabad", isDomestic: false },
  AMQ: { city: "Ambon", isDomestic: false },
  ANC: { city: "Anchorage", isDomestic: false },
  ANK: { city: "Ankara", isDomestic: false },
  AOR: { city: "Alor Setar", isDomestic: false },
  APL: { city: "Nampula", isDomestic: false },
  APN: { city: "Alpena", isDomestic: false },
  AQJ: { city: "Aqaba", isDomestic: false },
  ARH: { city: "Arkhangelsk", isDomestic: false },
  ARN: { city: "Stockholm", isDomestic: false },
  ARY: { city: "Ararat", isDomestic: false },
  ASE: { city: "Aspen", isDomestic: false },
  ASM: { city: "Asmara", isDomestic: false },
  ASR: { city: "Kayseri", isDomestic: false },
  ASU: { city: "Asuncion", isDomestic: false },
  ASW: { city: "Aswan", isDomestic: false },
  ATH: { city: "Athens", isDomestic: false },
  ATL: { city: "Atlanta", isDomestic: false },
  ATQ: { city: "Amritsar", isDomestic: false },
  ATZ: { city: "Assiut", isDomestic: false },
  AUS: { city: "Austin", isDomestic: false },
  AXD: { city: "Alexandroupoli", isDomestic: false },
  AYT: { city: "Antalya", isDomestic: false },
  AZO: { city: "Kalamazoo", isDomestic: false },
  BAL: { city: "Batman", isDomestic: false },
  BAR: { city: "Qionghai", isDomestic: false },
  BAV: { city: "Baotou", isDomestic: false },
  BAY: { city: "Baia Mare", isDomestic: false },
  BBI: { city: "Bhubaneswar", isDomestic: false },
  BCD: { city: "Bacolod", isDomestic: false },
  BDJ: { city: "Banjarmasin", isDomestic: false },
  BDO: { city: "Bandung", isDomestic: false },
  BDS: { city: "Brindisi", isDomestic: false },
  BEG: { city: "Belgrade", isDomestic: false },
  BER: { city: "Berlin", isDomestic: false },
  BES: { city: "Brest", isDomestic: false },
  BEY: { city: "Beirut", isDomestic: false },
  BFN: { city: "Bloemfontein", isDomestic: false },
  BGF: { city: "Bangui", isDomestic: false },
  BGG: { city: "Bingol", isDomestic: false },
  BGM: { city: "Binghamton", isDomestic: false },
  BGW: { city: "Baghdad", isDomestic: false },
  BHD: { city: "Belfast", isDomestic: false },
  BHI: { city: "Bahia Blanca", isDomestic: false },
  BHM: { city: "Birmingham", isDomestic: false },
  BHO: { city: "Bhopal", isDomestic: false },
  BHV: { city: "Bahawalpur", isDomestic: false },
  BHY: { city: "Beihai", isDomestic: false },
  BIA: { city: "Bastia", isDomestic: false },
  BIO: { city: "Bilbao", isDomestic: false },
  BIQ: { city: "Biarritz", isDomestic: false },
  BJI: { city: "Bemidji", isDomestic: false },
  BJL: { city: "Banjul", isDomestic: false },
  BJM: { city: "Bujumbura", isDomestic: false },
  BJS: { city: "Beijing", isDomestic: false },
  BJV: { city: "Bodrum", isDomestic: false },
  BJX: { city: "Leon", isDomestic: false },
  BJZ: { city: "Badajoz", isDomestic: false },
  BKI: { city: "Kota Kinabalu", isDomestic: false },
  BKO: { city: "Bamako", isDomestic: false },
  BKS: { city: "Bengkulu", isDomestic: false },
  BLQ: { city: "Bologna", isDomestic: false },
  BMI: { city: "Bloomington", isDomestic: false },
  BMV: { city: "Buon Ma Thuot", isDomestic: false },
  BNA: { city: "Nashville", isDomestic: false },
  BNE: { city: "Brisbane", isDomestic: false },
  BOD: { city: "Bordeaux", isDomestic: false },
  BOG: { city: "Bogota", isDomestic: false },
  BOI: { city: "Boise", isDomestic: false },
  BOO: { city: "Bodo", isDomestic: false },
  BOS: { city: "Boston", isDomestic: false },
  BPL: { city: "Bole", isDomestic: false },
  BPN: { city: "Balikpapan", isDomestic: false },
  BPS: { city: "Porto Seguro", isDomestic: false },
  BQK: { city: "Brunswick", isDomestic: false },
  BRC: { city: "Bariloche", isDomestic: false },
  BRD: { city: "Brainerd", isDomestic: false },
  BRE: { city: "Bremen", isDomestic: false },
  BRI: { city: "Bari", isDomestic: false },
  BRU: { city: "Brussels", isDomestic: false },
  BSB: { city: "Brasilia", isDomestic: false },
  BSD: { city: "Baoshan", isDomestic: false },
  BSR: { city: "Basra", isDomestic: false },
  BTH: { city: "Batam", isDomestic: false },
  BTJ: { city: "Banda Aceh", isDomestic: false },
  BTM: { city: "Butte", isDomestic: false },
  BTR: { city: "Baton Rouge", isDomestic: false },
  BTS: { city: "Bratislava", isDomestic: false },
  BTU: { city: "Bintulu", isDomestic: false },
  BUD: { city: "Budapest", isDomestic: false },
  BUE: { city: "Buenos Aires", isDomestic: false },
  BUF: { city: "Buffalo", isDomestic: false },
  BUH: { city: "Bucharest", isDomestic: false },
  BUS: { city: "Batumi", isDomestic: false },
  BWI: { city: "Baltimore", isDomestic: false },
  BWN: { city: "Bandar Seri Begawan", isDomestic: false },
  BWX: { city: "Banyuwangi", isDomestic: false },
  BXU: { city: "Butuan", isDomestic: false },
  BZL: { city: "Barisal", isDomestic: false },
  BZV: { city: "Brazzaville", isDomestic: false },
  BZX: { city: "Bazhong", isDomestic: false },
  CAE: { city: "Columbia", isDomestic: false },
  CAH: { city: "Can Tho", isDomestic: false },
  CBO: { city: "Cotabato", isDomestic: false },
  CCJ: { city: "Kozhikode", isDomestic: false },
  CCS: { city: "Caracas", isDomestic: false },
  CCU: { city: "Kolkata", isDomestic: false },
  CDC: { city: "Cedar City", isDomestic: false },
  CEB: { city: "Cebu", isDomestic: false },
  CEN: { city: "Ciudad Obregon", isDomestic: false },
  CFE: { city: "Clermont-Ferrand", isDomestic: false },
  CFU: { city: "Corfu", isDomestic: false },
  CGK: { city: "Jakarta", isDomestic: false },
  CGN: { city: "Cologne", isDomestic: false },
  CGO: { city: "Zhengzhou", isDomestic: false },
  CGP: { city: "Chittagong", isDomestic: false },
  CGQ: { city: "Changchun", isDomestic: false },
  CGY: { city: "Cagayan de Oro", isDomestic: false },
  CHC: { city: "Christchurch", isDomestic: false },
  CHG: { city: "Chaoyang", isDomestic: false },
  CHI: { city: "Chicago", isDomestic: false },
  CHQ: { city: "Chania", isDomestic: false },
  CIU: { city: "Sault Ste. Marie", isDomestic: false },
  CJB: { city: "Coimbatore", isDomestic: false },
  CJS: { city: "Ciudad Juarez", isDomestic: false },
  CJU: { city: "Jeju", isDomestic: false },
  CKG: { city: "Chongqing", isDomestic: false },
  CKY: { city: "Conakry", isDomestic: false },
  CLE: { city: "Cleveland", isDomestic: false },
  CLJ: { city: "Cluj-Napoca", isDomestic: false },
  CLO: { city: "Cali", isDomestic: false },
  CLQ: { city: "Colima", isDomestic: false },
  CLT: { city: "Charlotte", isDomestic: false },
  CLY: { city: "Calvi", isDomestic: false },
  CMB: { city: "Colombo", isDomestic: false },
  CME: { city: "Ciudad del Carmen", isDomestic: false },
  CMH: { city: "Columbus", isDomestic: false },
  CNQ: { city: "Corrientes", isDomestic: false },
  CNX: { city: "Chiang Mai", isDomestic: false },
  COO: { city: "Cotonou", isDomestic: false },
  COR: { city: "Cordoba", isDomestic: false },
  CPC: { city: "San Martin de los Andes", isDomestic: false },
  CPE: { city: "Campeche", isDomestic: false },
  CPH: { city: "Copenhagen", isDomestic: false },
  CPT: { city: "Cape Town", isDomestic: false },
  CRD: { city: "Comodoro Rivadavia", isDomestic: false },
  CRW: { city: "Charleston", isDomestic: false },
  CSG: { city: "Columbus", isDomestic: false },
  CSX: { city: "Changsha", isDomestic: false },
  CTA: { city: "Catania", isDomestic: false },
  CTC: { city: "Catamarca", isDomestic: false },
  CTM: { city: "Chetumal", isDomestic: false },
  CTS: { city: "Sapporo", isDomestic: false },
  CTU: { city: "Chengdu", isDomestic: false },
  CUL: { city: "Culiacan", isDomestic: false },
  CUN: { city: "Cancun", isDomestic: false },
  CUU: { city: "Chihuahua", isDomestic: false },
  CUZ: { city: "Cusco", isDomestic: false },
  CVG: { city: "Cincinnati", isDomestic: false },
  CWA: { city: "Wausau", isDomestic: false },
  CWB: { city: "Curitiba", isDomestic: false },
  CWJ: { city: "Cangyuan", isDomestic: false },
  CWL: { city: "Cardiff", isDomestic: false },
  CXB: { city: "Cox's Bazar", isDomestic: false },
  CXR: { city: "Nha Trang", isDomestic: false },
  CZL: { city: "Constantine", isDomestic: false },
  CZX: { city: "Changzhou", isDomestic: false },
  DAB: { city: "Daytona Beach", isDomestic: false },
  DAD: { city: "Da Nang", isDomestic: false },
  DAL: { city: "Dallas", isDomestic: false },
  DAM: { city: "Damascus", isDomestic: false },
  DAR: { city: "Dar es Salaam", isDomestic: false },
  DAT: { city: "Datong", isDomestic: false },
  DAY: { city: "Dayton", isDomestic: false },
  DBB: { city: "Dabaa", isDomestic: false },
  DBV: { city: "Dubrovnik", isDomestic: false },
  DCA: { city: "Washington", isDomestic: false },
  DED: { city: "Dehradun", isDomestic: false },
  DEN: { city: "Denver", isDomestic: false },
  DFW: { city: "Dallas", isDomestic: false },
  DGO: { city: "Durango", isDomestic: false },
  DGT: { city: "Dumaguete", isDomestic: false },
  DHN: { city: "Dothan", isDomestic: false },
  DIB: { city: "Dibrugarh", isDomestic: false },
  DIG: { city: "Diqing", isDomestic: false },
  DIN: { city: "Dien Bien Phu", isDomestic: false },
  DIY: { city: "Diyarbakir", isDomestic: false },
  DJB: { city: "Jambi", isDomestic: false },
  DJE: { city: "Djerba", isDomestic: false },
  DJJ: { city: "Jayapura", isDomestic: false },
  DKR: { city: "Dakar", isDomestic: false },
  DLA: { city: "Douala", isDomestic: false },
  DLC: { city: "Dalian", isDomestic: false },
  DLI: { city: "Da Lat", isDomestic: false },
  DLM: { city: "Dalaman", isDomestic: false },
  DLU: { city: "Dali", isDomestic: false },
  DMU: { city: "Dimapur", isDomestic: false },
  DNH: { city: "Dunhuang", isDomestic: false },
  DNZ: { city: "Denizli", isDomestic: false },
  DOY: { city: "Dongying", isDomestic: false },
  DPL: { city: "Dipolog", isDomestic: false },
  DQA: { city: "Daqing", isDomestic: false },
  DSN: { city: "Ordos", isDomestic: false },
  DSS: { city: "Dakar", isDomestic: false },
  DTT: { city: "Detroit", isDomestic: false },
  DTW: { city: "Detroit", isDomestic: false },
  DUB: { city: "Dublin", isDomestic: false },
  DUR: { city: "Durban", isDomestic: false },
  DUS: { city: "Dusseldorf", isDomestic: false },
  DVO: { city: "Davao", isDomestic: false },
  DYG: { city: "Zhangjiajie", isDomestic: false },
  DZA: { city: "Dzaoudzi", isDomestic: false },
  DZH: { city: "Dazhou", isDomestic: false },
  EAS: { city: "San Sebastian", isDomestic: false },
  EBB: { city: "Entebbe", isDomestic: false },
  EBL: { city: "Erbil", isDomestic: false },
  ECP: { city: "Panama City", isDomestic: false },
  EDI: { city: "Edinburgh", isDomestic: false },
  EDL: { city: "Eldoret", isDomestic: false },
  EDO: { city: "Balikesir", isDomestic: false },
  EFL: { city: "Kefalonia", isDomestic: false },
  EHU: { city: "Ezhou", isDomestic: false },
  EKO: { city: "Elko", isDomestic: false },
  ELH: { city: "North Eleuthera", isDomestic: false },
  ELM: { city: "Elmira", isDomestic: false },
  ELS: { city: "East London", isDomestic: false },
  ENH: { city: "Enshi", isDomestic: false },
  ENU: { city: "Enugu", isDomestic: false },
  ENY: { city: "Yan'an", isDomestic: false },
  EQS: { city: "Esquel", isDomestic: false },
  ERC: { city: "Erzincan", isDomestic: false },
  ERZ: { city: "Erzurum", isDomestic: false },
  ESB: { city: "Ankara", isDomestic: false },
  ESC: { city: "Escanaba", isDomestic: false },
  EUG: { city: "Eugene", isDomestic: false },
  EUN: { city: "Laayoune", isDomestic: false },
  EVN: { city: "Yerevan", isDomestic: false },
  EVV: { city: "Evansville", isDomestic: false },
  EWR: { city: "Newark", isDomestic: false },
  EXT: { city: "Exeter", isDomestic: false },
  EZS: { city: "Elazig", isDomestic: false },
  FAE: { city: "Faroe Islands", isDomestic: false },
  FAI: { city: "Fairbanks", isDomestic: false },
  FBM: { city: "Lubumbashi", isDomestic: false },
  FCA: { city: "Kalispell", isDomestic: false },
  FDH: { city: "Friedrichshafen", isDomestic: false },
  FEZ: { city: "Fez", isDomestic: false },
  FIH: { city: "Kinshasa", isDomestic: false },
  FKB: { city: "Karlsruhe", isDomestic: false },
  FLN: { city: "Florianopolis", isDomestic: false },
  FLR: { city: "Florence", isDomestic: false },
  FLZ: { city: "Sibolga", isDomestic: false },
  FMA: { city: "Formosa", isDomestic: false },
  FNA: { city: "Freetown", isDomestic: false },
  FNC: { city: "Funchal", isDomestic: false },
  FOC: { city: "Fuzhou", isDomestic: false },
  FSC: { city: "Figari", isDomestic: false },
  FSZ: { city: "Shizuoka", isDomestic: false },
  FTE: { city: "El Calafate", isDomestic: false },
  FUE: { city: "Fuerteventura", isDomestic: false },
  FUG: { city: "Fuyang", isDomestic: false },
  FUK: { city: "Fukuoka", isDomestic: false },
  FWA: { city: "Fort Wayne", isDomestic: false },
  GAU: { city: "Guwahati", isDomestic: false },
  GAY: { city: "Gaya", isDomestic: false },
  GBE: { city: "Gaborone", isDomestic: false },
  GDL: { city: "Guadalajara", isDomestic: false },
  GDN: { city: "Gdansk", isDomestic: false },
  GEG: { city: "Spokane", isDomestic: false },
  GEO: { city: "Georgetown", isDomestic: false },
  GES: { city: "General Santos", isDomestic: false },
  GIG: { city: "Rio de Janeiro", isDomestic: false },
  GJT: { city: "Grand Junction", isDomestic: false },
  GLA: { city: "Glasgow", isDomestic: false },
  GMP: { city: "Seoul", isDomestic: false },
  GMQ: { city: "Golog", isDomestic: false },
  GMZ: { city: "San Sebastian de la Gomera", isDomestic: false },
  GND: { city: "Grenada", isDomestic: false },
  GNS: { city: "Gunungsitoli", isDomestic: false },
  GNV: { city: "Gainesville", isDomestic: false },
  GNY: { city: "Sanliurfa", isDomestic: false },
  GOA: { city: "Genoa", isDomestic: false },
  GOH: { city: "Nuuk", isDomestic: false },
  GOI: { city: "Goa", isDomestic: false },
  GOQ: { city: "Golmud", isDomestic: false },
  GOT: { city: "Gothenburg", isDomestic: false },
  GRJ: { city: "George", isDomestic: false },
  GRO: { city: "Girona", isDomestic: false },
  GRU: { city: "Sao Paulo", isDomestic: false },
  GRX: { city: "Granada", isDomestic: false },
  GRZ: { city: "Graz", isDomestic: false },
  GTF: { city: "Great Falls", isDomestic: false },
  GTO: { city: "Gorontalo", isDomestic: false },
  GTR: { city: "Columbus", isDomestic: false },
  GWD: { city: "Gwadar", isDomestic: false },
  GYD: { city: "Baku", isDomestic: false },
  GYE: { city: "Guayaquil", isDomestic: false },
  GYS: { city: "Guangyuan", isDomestic: false },
  GYU: { city: "Guyuan", isDomestic: false },
  GZP: { city: "Gazipasa", isDomestic: false },
  GZT: { city: "Gaziantep", isDomestic: false },
  HAD: { city: "Halmstad", isDomestic: false },
  HAH: { city: "Moroni", isDomestic: false },
  HAJ: { city: "Hanover", isDomestic: false },
  HAK: { city: "Haikou", isDomestic: false },
  HAM: { city: "Hamburg", isDomestic: false },
  HAN: { city: "Hanoi", isDomestic: false },
  HAU: { city: "Haugesund", isDomestic: false },
  HAV: { city: "Havana", isDomestic: false },
  HBQ: { city: "Qinhuangdao", isDomestic: false },
  HDG: { city: "Handan", isDomestic: false },
  HDY: { city: "Hat Yai", isDomestic: false },
  HEK: { city: "Heihe", isDomestic: false },
  HEL: { city: "Helsinki", isDomestic: false },
  HER: { city: "Heraklion", isDomestic: false },
  HET: { city: "Hohhot", isDomestic: false },
  HFE: { city: "Hefei", isDomestic: false },
  HGA: { city: "Hargeisa", isDomestic: false },
  HGH: { city: "Hangzhou", isDomestic: false },
  HGN: { city: "Mae Hong Son", isDomestic: false },
  HHH: { city: "Hilton Head", isDomestic: false },
  HIA: { city: "Huai'an", isDomestic: false },
  HIB: { city: "Hibbing", isDomestic: false },
  HIJ: { city: "Hiroshima", isDomestic: false },
  HJR: { city: "Khajuraho", isDomestic: false },
  HKG: { city: "Hong Kong", isDomestic: false },
  HKT: { city: "Phuket", isDomestic: false },
  HLD: { city: "Hailar", isDomestic: false },
  HLN: { city: "Helena", isDomestic: false },
  HLP: { city: "Jakarta", isDomestic: false },
  HMB: { city: "Sohag", isDomestic: false },
  HMO: { city: "Hermosillo", isDomestic: false },
  HND: { city: "Tokyo", isDomestic: false },
  HNL: { city: "Honolulu", isDomestic: false },
  HNY: { city: "Hengyang", isDomestic: false },
  HOF: { city: "Al Hofuf", isDomestic: false },
  HOU: { city: "Houston", isDomestic: false },
  HPH: { city: "Hai Phong", isDomestic: false },
  HRB: { city: "Harbin", isDomestic: false },
  HRE: { city: "Harare", isDomestic: false },
  HRG: { city: "Hurghada", isDomestic: false },
  HRK: { city: "Kharkiv", isDomestic: false },
  HSN: { city: "Zhoushan", isDomestic: false },
  HSV: { city: "Huntsville", isDomestic: false },
  HTN: { city: "Hotan", isDomestic: false },
  HTT: { city: "Huatugou", isDomestic: false },
  HTY: { city: "Hatay", isDomestic: false },
  HUI: { city: "Hue", isDomestic: false },
  HUX: { city: "Huatulco", isDomestic: false },
  HUY: { city: "Humberside", isDomestic: false },
  HUZ: { city: "Huizhou", isDomestic: false },
  HXD: { city: "Hilton Head", isDomestic: false },
  HYN: { city: "Taizhou", isDomestic: false },
  HZA: { city: "Heze", isDomestic: false },
  HZG: { city: "Hanzhong", isDomestic: false },
  IAS: { city: "Iasi", isDomestic: false },
  IBZ: { city: "Ibiza", isDomestic: false },
  ICN: { city: "Seoul", isDomestic: false },
  ICO: { city: "Sicogon Island", isDomestic: false },
  ICT: { city: "Wichita", isDomestic: false },
  IDR: { city: "Indore", isDomestic: false },
  IEV: { city: "Kyiv", isDomestic: false },
  IGD: { city: "Igdir", isDomestic: false },
  IGR: { city: "Puerto Iguazu", isDomestic: false },
  ILO: { city: "Iloilo", isDomestic: false },
  IMF: { city: "Imphal", isDomestic: false },
  IMT: { city: "Iron Mountain", isDomestic: false },
  INC: { city: "Yinchuan", isDomestic: false },
  IND: { city: "Indianapolis", isDomestic: false },
  INL: { city: "International Falls", isDomestic: false },
  INV: { city: "Inverness", isDomestic: false },
  IOA: { city: "Ioannina", isDomestic: false },
  IRJ: { city: "La Rioja", isDomestic: false },
  ISE: { city: "Isparta", isDomestic: false },
  ISU: { city: "Sulaymaniyah", isDomestic: false },
  ITH: { city: "Ithaca", isDomestic: false },
  IXA: { city: "Agartala", isDomestic: false },
  IXB: { city: "Bagdogra", isDomestic: false },
  IXC: { city: "Chandigarh", isDomestic: false },
  IXE: { city: "Mangalore", isDomestic: false },
  IXJ: { city: "Jammu", isDomestic: false },
  IXL: { city: "Leh", isDomestic: false },
  IXM: { city: "Madurai", isDomestic: false },
  IXR: { city: "Ranchi", isDomestic: false },
  IXS: { city: "Silchar", isDomestic: false },
  IXU: { city: "Aurangabad", isDomestic: false },
  IXZ: { city: "Port Blair", isDomestic: false },
  JAC: { city: "Jackson", isDomestic: false },
  JAI: { city: "Jaipur", isDomestic: false },
  JAN: { city: "Jackson", isDomestic: false },
  JAX: { city: "Jacksonville", isDomestic: false },
  JBB: { city: "Jambi", isDomestic: false },
  JDH: { city: "Jodhpur", isDomestic: false },
  JDZ: { city: "Jingdezhen", isDomestic: false },
  JGA: { city: "Jamnagar", isDomestic: false },
  JGD: { city: "Jiagedaqi", isDomestic: false },
  JGN: { city: "Jiayuguan", isDomestic: false },
  JGS: { city: "Ji'an", isDomestic: false },
  JHB: { city: "Johor Bahru", isDomestic: false },
  JHG: { city: "Jinghong", isDomestic: false },
  JIB: { city: "Djibouti", isDomestic: false },
  JIC: { city: "Jinchang", isDomestic: false },
  JIQ: { city: "Qianjiang", isDomestic: false },
  JJN: { city: "Quanzhou", isDomestic: false },
  JKH: { city: "Chios", isDomestic: false },
  JMJ: { city: "Lancang", isDomestic: false },
  JMK: { city: "Mykonos", isDomestic: false },
  JMU: { city: "Jiamusi", isDomestic: false },
  JNB: { city: "Johannesburg", isDomestic: false },
  JNU: { city: "Juneau", isDomestic: false },
  JNZ: { city: "Jinzhou", isDomestic: false },
  JOG: { city: "Yogyakarta", isDomestic: false },
  JRO: { city: "Kilimanjaro", isDomestic: false },
  JSR: { city: "Jessore", isDomestic: false },
  JTR: { city: "Santorini", isDomestic: false },
  JUB: { city: "Juba", isDomestic: false },
  JUJ: { city: "Jujuy", isDomestic: false },
  JUZ: { city: "Quzhou", isDomestic: false },
  KBR: { city: "Kota Bharu", isDomestic: false },
  KBV: { city: "Krabi", isDomestic: false },
  KCA: { city: "Kuqa", isDomestic: false },
  KCH: { city: "Kuching", isDomestic: false },
  KCM: { city: "Kahramanmaras", isDomestic: false },
  KDI: { city: "Kendari", isDomestic: false },
  KFS: { city: "Kastamonu", isDomestic: false },
  KGL: { city: "Kigali", isDomestic: false },
  KGS: { city: "Kos", isDomestic: false },
  KHE: { city: "Kherson", isDomestic: false },
  KHG: { city: "Kashgar", isDomestic: false },
  KHH: { city: "Kaohsiung", isDomestic: false },
  KHN: { city: "Nanchang", isDomestic: false },
  KIM: { city: "Kimberley", isDomestic: false },
  KIS: { city: "Kisumu", isDomestic: false },
  KIX: { city: "Osaka", isDomestic: false },
  KKN: { city: "Kirkenes", isDomestic: false },
  KLO: { city: "Kalibo", isDomestic: false },
  KLR: { city: "Kalmar", isDomestic: false },
  KLX: { city: "Kalamata", isDomestic: false },
  KMG: { city: "Kunming", isDomestic: false },
  KMJ: { city: "Kumamoto", isDomestic: false },
  KNO: { city: "Medan", isDomestic: false },
  KOA: { city: "Kailua-Kona", isDomestic: false },
  KOE: { city: "Kupang", isDomestic: false },
  KOW: { city: "Ganzhou", isDomestic: false },
  KRK: { city: "Krakow", isDomestic: false },
  KRL: { city: "Korla", isDomestic: false },
  KRN: { city: "Kiruna", isDomestic: false },
  KRR: { city: "Krasnodar", isDomestic: false },
  KRS: { city: "Kristiansand", isDomestic: false },
  KRT: { city: "Khartoum", isDomestic: false },
  KRY: { city: "Karamay", isDomestic: false },
  KSC: { city: "Kosice", isDomestic: false },
  KSU: { city: "Kristiansund", isDomestic: false },
  KSY: { city: "Kars", isDomestic: false },
  KTM: { city: "Kathmandu", isDomestic: false },
  KUA: { city: "Kuantan", isDomestic: false },
  KUF: { city: "Samara", isDomestic: false },
  KVA: { city: "Kavala", isDomestic: false },
  KWE: { city: "Guiyang", isDomestic: false },
  KWL: { city: "Guilin", isDomestic: false },
  KYA: { city: "Konya", isDomestic: false },
  KZN: { city: "Kazan", isDomestic: false },
  KZR: { city: "Kutahya", isDomestic: false },
  LAD: { city: "Luanda", isDomestic: false },
  LAN: { city: "Lansing", isDomestic: false },
  LAO: { city: "Laoag", isDomestic: false },
  LAP: { city: "La Paz", isDomestic: false },
  LAS: { city: "Las Vegas", isDomestic: false },
  LAX: { city: "Los Angeles", isDomestic: false },
  LBA: { city: "Leeds", isDomestic: false },
  LBJ: { city: "Labuan Bajo", isDomestic: false },
  LBU: { city: "Labuan", isDomestic: false },
  LBV: { city: "Libreville", isDomestic: false },
  LCA: { city: "Larnaca", isDomestic: false },
  LCG: { city: "La Coruna", isDomestic: false },
  LCY: { city: "London", isDomestic: false },
  LDS: { city: "Yichun", isDomestic: false },
  LED: { city: "Saint Petersburg", isDomestic: false },
  LEI: { city: "Almeria", isDomestic: false },
  LEJ: { city: "Leipzig", isDomestic: false },
  LFT: { city: "Lafayette", isDomestic: false },
  LFW: { city: "Lome", isDomestic: false },
  LGK: { city: "Langkawi", isDomestic: false },
  LGP: { city: "Legazpi", isDomestic: false },
  LHW: { city: "Lanzhou", isDomestic: false },
  LIH: { city: "Lihue", isDomestic: false },
  LIL: { city: "Lille", isDomestic: false },
  LIM: { city: "Lima", isDomestic: false },
  LIN: { city: "Milan", isDomestic: false },
  LIS: { city: "Lisbon", isDomestic: false },
  LJG: { city: "Lijiang", isDomestic: false },
  LJU: { city: "Ljubljana", isDomestic: false },
  LLA: { city: "Lulea", isDomestic: false },
  LLV: { city: "Lvliang", isDomestic: false },
  LLW: { city: "Lilongwe", isDomestic: false },
  LMM: { city: "Los Mochis", isDomestic: false },
  LMP: { city: "Lampedusa", isDomestic: false },
  LNJ: { city: "Lincang", isDomestic: false },
  LON: { city: "London", isDomestic: false },
  LOP: { city: "Lombok", isDomestic: false },
  LPA: { city: "Las Palmas", isDomestic: false },
  LPI: { city: "Linkoping", isDomestic: false },
  LPQ: { city: "Luang Prabang", isDomestic: false },
  LPT: { city: "Lampang", isDomestic: false },
  LSW: { city: "Lhokseumawe", isDomestic: false },
  LUM: { city: "Mangshi", isDomestic: false },
  LUN: { city: "Lusaka", isDomestic: false },
  LUQ: { city: "San Luis", isDomestic: false },
  LUX: { city: "Luxembourg", isDomestic: false },
  LVI: { city: "Livingstone", isDomestic: false },
  LWS: { city: "Lewiston", isDomestic: false },
  LXA: { city: "Lhasa", isDomestic: false },
  LXR: { city: "Luxor", isDomestic: false },
  LXS: { city: "Lemnos", isDomestic: false },
  LYA: { city: "Luoyang", isDomestic: false },
  LYG: { city: "Lianyungang", isDomestic: false },
  LYI: { city: "Linyi", isDomestic: false },
  LYP: { city: "Faisalabad", isDomestic: false },
  LYR: { city: "Longyearbyen", isDomestic: false },
  LYS: { city: "Lyon", isDomestic: false },
  LZH: { city: "Liuzhou", isDomestic: false },
  LZO: { city: "Luzhou", isDomestic: false },
  MAA: { city: "Chennai", isDomestic: false },
  MAF: { city: "Midland", isDomestic: false },
  MAH: { city: "Menorca", isDomestic: false },
  MAM: { city: "Matamoros", isDomestic: false },
  MAQ: { city: "Mae Sot", isDomestic: false },
  MBA: { city: "Mombasa", isDomestic: false },
  MBS: { city: "Saginaw", isDomestic: false },
  MCI: { city: "Kansas City", isDomestic: false },
  MCO: { city: "Orlando", isDomestic: false },
  MCT: { city: "Muscat", isDomestic: false },
  MDC: { city: "Manado", isDomestic: false },
  MDG: { city: "Mudanjiang", isDomestic: false },
  MDL: { city: "Mandalay", isDomestic: false },
  MDQ: { city: "Mar del Plata", isDomestic: false },
  MDT: { city: "Harrisburg", isDomestic: false },
  MDW: { city: "Chicago", isDomestic: false },
  MDZ: { city: "Mendoza", isDomestic: false },
  MEL: { city: "Melbourne", isDomestic: false },
  MEM: { city: "Memphis", isDomestic: false },
  MES: { city: "Medan", isDomestic: false },
  MEX: { city: "Mexico City", isDomestic: false },
  MFE: { city: "McAllen", isDomestic: false },
  MFM: { city: "Macau", isDomestic: false },
  MFR: { city: "Medford", isDomestic: false },
  MGA: { city: "Managua", isDomestic: false },
  MGM: { city: "Montgomery", isDomestic: false },
  MGQ: { city: "Mogadishu", isDomestic: false },
  MHH: { city: "Marsh Harbour", isDomestic: false },
  MIA: { city: "Miami", isDomestic: false },
  MID: { city: "Merida", isDomestic: false },
  MIG: { city: "Mianyang", isDomestic: false },
  MIL: { city: "Milan", isDomestic: false },
  MIR: { city: "Monastir", isDomestic: false },
  MJT: { city: "Mytilene", isDomestic: false },
  MJV: { city: "Murcia", isDomestic: false },
  MKC: { city: "Kansas City", isDomestic: false },
  MKQ: { city: "Merauke", isDomestic: false },
  MLA: { city: "Valletta", isDomestic: false },
  MLB: { city: "Melbourne", isDomestic: false },
  MLG: { city: "Malang", isDomestic: false },
  MLI: { city: "Moline", isDomestic: false },
  MLM: { city: "Morelia", isDomestic: false },
  MLW: { city: "Monrovia", isDomestic: false },
  MLX: { city: "Malatya", isDomestic: false },
  MMA: { city: "Malmo", isDomestic: false },
  MME: { city: "Teesside", isDomestic: false },
  MMX: { city: "Malmo", isDomestic: false },
  MOW: { city: "Moscow", isDomestic: false },
  MPL: { city: "Montpellier", isDomestic: false },
  MPM: { city: "Maputo", isDomestic: false },
  MQM: { city: "Mardin", isDomestic: false },
  MQP: { city: "Nelspruit", isDomestic: false },
  MQT: { city: "Marquette", isDomestic: false },
  MRS: { city: "Marseille", isDomestic: false },
  MSO: { city: "Missoula", isDomestic: false },
  MSP: { city: "Minneapolis", isDomestic: false },
  MSR: { city: "Mus", isDomestic: false },
  MSU: { city: "Maseru", isDomestic: false },
  MTT: { city: "Minatitlan", isDomestic: false },
  MTY: { city: "Monterrey", isDomestic: false },
  MVD: { city: "Montevideo", isDomestic: false },
  MXL: { city: "Mexicali", isDomestic: false },
  MYY: { city: "Miri", isDomestic: false },
  MZH: { city: "Merzifon", isDomestic: false },
  MZT: { city: "Mazatlan", isDomestic: false },
  NAG: { city: "Nagpur", isDomestic: false },
  NAO: { city: "Nanchong", isDomestic: false },
  NAP: { city: "Naples", isDomestic: false },
  NAV: { city: "Nevsehir", isDomestic: false },
  NBS: { city: "Baishan", isDomestic: false },
  NCE: { city: "Nice", isDomestic: false },
  NCL: { city: "Newcastle", isDomestic: false },
  NDG: { city: "Qiqihar", isDomestic: false },
  NDJ: { city: "N'Djamena", isDomestic: false },
  NDR: { city: "Nador", isDomestic: false },
  NDS: { city: "Sandstone", isDomestic: false },
  NGB: { city: "Ningbo", isDomestic: false },
  NGO: { city: "Nagoya", isDomestic: false },
  NGQ: { city: "Shiquanhe", isDomestic: false },
  NGS: { city: "Nagasaki", isDomestic: false },
  NIM: { city: "Niamey", isDomestic: false },
  NJF: { city: "Najaf", isDomestic: false },
  NKC: { city: "Nouakchott", isDomestic: false },
  NKG: { city: "Nanjing", isDomestic: false },
  NKT: { city: "Sirnak", isDomestic: false },
  NLA: { city: "Ndola", isDomestic: false },
  NLD: { city: "Nuevo Laredo", isDomestic: false },
  NLH: { city: "Ninglang", isDomestic: false },
  NLU: { city: "Mexico City", isDomestic: false },
  NNG: { city: "Nanning", isDomestic: false },
  NOP: { city: "Sinop", isDomestic: false },
  NQN: { city: "Neuquen", isDomestic: false },
  NQZ: { city: "Astana", isDomestic: false },
  NRT: { city: "Tokyo", isDomestic: false },
  NSI: { city: "Yaounde", isDomestic: false },
  NTE: { city: "Nantes", isDomestic: false },
  NTG: { city: "Nantong", isDomestic: false },
  NUE: { city: "Nuremberg", isDomestic: false },
  NWI: { city: "Norwich", isDomestic: false },
  NYC: { city: "New York City", isDomestic: false },
  NYT: { city: "Naypyidaw", isDomestic: false },
  OAJ: { city: "Jacksonville", isDomestic: false },
  OAK: { city: "Oakland", isDomestic: false },
  OAX: { city: "Oaxaca", isDomestic: false },
  ODB: { city: "Cordoba", isDomestic: false },
  ODS: { city: "Odesa", isDomestic: false },
  OGG: { city: "Kahului", isDomestic: false },
  OGU: { city: "Ordu", isDomestic: false },
  OKC: { city: "Oklahoma City", isDomestic: false },
  OMO: { city: "Mostar", isDomestic: false },
  OMR: { city: "Oradea", isDomestic: false },
  ONQ: { city: "Zonguldak", isDomestic: false },
  OPO: { city: "Porto", isDomestic: false },
  ORD: { city: "Chicago", isDomestic: false },
  ORL: { city: "Orlando", isDomestic: false },
  ORY: { city: "Paris", isDomestic: false },
  OSA: { city: "Osaka", isDomestic: false },
  OSD: { city: "Ostersund", isDomestic: false },
  OSL: { city: "Oslo", isDomestic: false },
  OSR: { city: "Ostrava", isDomestic: false },
  OTP: { city: "Bucharest", isDomestic: false },
  OUA: { city: "Ouagadougou", isDomestic: false },
  OUD: { city: "Oujda", isDomestic: false },
  OVD: { city: "Oviedo", isDomestic: false },
  OZH: { city: "Zaporizhzhia", isDomestic: false },
  OZZ: { city: "Ouarzazate", isDomestic: false },
  PAR: { city: "Paris", isDomestic: false },
  PAT: { city: "Patna", isDomestic: false },
  PBM: { city: "Paramaribo", isDomestic: false },
  PDG: { city: "Padang", isDomestic: false },
  PDP: { city: "Punta del Este", isDomestic: false },
  PDX: { city: "Portland", isDomestic: false },
  PEK: { city: "Beijing", isDomestic: false },
  PEN: { city: "Penang", isDomestic: false },
  PER: { city: "Perth", isDomestic: false },
  PGK: { city: "Pangkal Pinang", isDomestic: false },
  PHL: { city: "Philadelphia", isDomestic: false },
  PHW: { city: "Phalaborwa", isDomestic: false },
  PHX: { city: "Phoenix", isDomestic: false },
  PIH: { city: "Pocatello", isDomestic: false },
  PIT: { city: "Pittsburgh", isDomestic: false },
  PKU: { city: "Pekanbaru", isDomestic: false },
  PKY: { city: "Palangkaraya", isDomestic: false },
  PLM: { city: "Palembang", isDomestic: false },
  PLN: { city: "Pellston", isDomestic: false },
  PLQ: { city: "Palanga", isDomestic: false },
  PLW: { city: "Palu", isDomestic: false },
  PLZ: { city: "Port Elizabeth", isDomestic: false },
  PMI: { city: "Palma de Mallorca", isDomestic: false },
  PMO: { city: "Palermo", isDomestic: false },
  PMY: { city: "Puerto Madryn", isDomestic: false },
  PNH: { city: "Phnom Penh", isDomestic: false },
  PNK: { city: "Pontianak", isDomestic: false },
  PNL: { city: "Pantelleria", isDomestic: false },
  PNQ: { city: "Pune", isDomestic: false },
  PNR: { city: "Pointe-Noire", isDomestic: false },
  PNS: { city: "Pensacola", isDomestic: false },
  POA: { city: "Porto Alegre", isDomestic: false },
  POZ: { city: "Poznan", isDomestic: false },
  PPS: { city: "Puerto Princesa", isDomestic: false },
  PQC: { city: "Phu Quoc", isDomestic: false },
  PRA: { city: "Parana", isDomestic: false },
  PRG: { city: "Prague", isDomestic: false },
  PRN: { city: "Pristina", isDomestic: false },
  PSA: { city: "Pisa", isDomestic: false },
  PSC: { city: "Pasco", isDomestic: false },
  PSP: { city: "Palm Springs", isDomestic: false },
  PSR: { city: "Pescara", isDomestic: false },
  PSS: { city: "Posadas", isDomestic: false },
  PTG: { city: "Polokwane", isDomestic: false },
  PTY: { city: "Panama City", isDomestic: false },
  PUF: { city: "Pau", isDomestic: false },
  PUS: { city: "Busan", isDomestic: false },
  PUW: { city: "Pullman", isDomestic: false },
  PUY: { city: "Pula", isDomestic: false },
  PVG: { city: "Shanghai", isDomestic: false },
  PVR: { city: "Puerto Vallarta", isDomestic: false },
  PXM: { city: "Puerto Escondido", isDomestic: false },
  PXU: { city: "Pleiku", isDomestic: false },
  PZB: { city: "Pietermaritzburg", isDomestic: false },
  QRO: { city: "Queretaro", isDomestic: false },
  QSZ: { city: "Shache", isDomestic: false },
  RAJ: { city: "Rajkot", isDomestic: false },
  RAK: { city: "Marrakesh", isDomestic: false },
  RAP: { city: "Rapid City", isDomestic: false },
  RBA: { city: "Rabat", isDomestic: false },
  RCB: { city: "Richards Bay", isDomestic: false },
  RCU: { city: "Rio Cuarto", isDomestic: false },
  RDM: { city: "Redmond", isDomestic: false },
  RDU: { city: "Raleigh", isDomestic: false },
  REG: { city: "Reggio Calabria", isDomestic: false },
  REK: { city: "Reykjavik", isDomestic: false },
  REL: { city: "Trelew", isDomestic: false },
  REP: { city: "Siem Reap", isDomestic: false },
  RES: { city: "Resistencia", isDomestic: false },
  REU: { city: "Reus", isDomestic: false },
  REX: { city: "Reynosa", isDomestic: false },
  RGA: { city: "Rio Grande", isDomestic: false },
  RGL: { city: "Rio Gallegos", isDomestic: false },
  RGN: { city: "Yangon", isDomestic: false },
  RGS: { city: "Burgos", isDomestic: false },
  RHD: { city: "Rio Hondo", isDomestic: false },
  RHI: { city: "Rhinelander", isDomestic: false },
  RHO: { city: "Rhodes", isDomestic: false },
  RIO: { city: "Rio de Janeiro", isDomestic: false },
  RIZ: { city: "Rizhao", isDomestic: false },
  RJH: { city: "Rajshahi", isDomestic: false },
  RKZ: { city: "Shigatse", isDomestic: false },
  RLK: { city: "Bayannur", isDomestic: false },
  RLO: { city: "Merlo", isDomestic: false },
  RMQ: { city: "Taichung", isDomestic: false },
  RNB: { city: "Ronneby", isDomestic: false },
  RNN: { city: "Bornholm", isDomestic: false },
  RNS: { city: "Rennes", isDomestic: false },
  ROC: { city: "Rochester", isDomestic: false },
  ROM: { city: "Rome", isDomestic: false },
  ROR: { city: "Koror", isDomestic: false },
  ROS: { city: "Rosario", isDomestic: false },
  ROV: { city: "Rostov-on-Don", isDomestic: false },
  RPR: { city: "Raipur", isDomestic: false },
  RSA: { city: "Santa Rosa", isDomestic: false },
  RST: { city: "Rochester", isDomestic: false },
  RXS: { city: "Roxas", isDomestic: false },
  RYK: { city: "Rahim Yar Khan", isDomestic: false },
  RZV: { city: "Rize", isDomestic: false },
  SAI: { city: "Siem Reap", isDomestic: false },
  SAN: { city: "San Diego", isDomestic: false },
  SAO: { city: "Sao Paulo", isDomestic: false },
  SAT: { city: "San Antonio", isDomestic: false },
  SBG: { city: "Sabang", isDomestic: false },
  SBN: { city: "South Bend", isDomestic: false },
  SBW: { city: "Sibu", isDomestic: false },
  SCL: { city: "Santiago", isDomestic: false },
  SCO: { city: "Aktau", isDomestic: false },
  SCQ: { city: "Santiago de Compostela", isDomestic: false },
  SCR: { city: "Sveg", isDomestic: false },
  SCV: { city: "Suceava", isDomestic: false },
  SDE: { city: "Santiago del Estero", isDomestic: false },
  SDL: { city: "Sundsvall", isDomestic: false },
  SDR: { city: "Santander", isDomestic: false },
  SEA: { city: "Seattle", isDomestic: false },
  SEL: { city: "Seoul", isDomestic: false },
  SEZ: { city: "Mahe", isDomestic: false },
  SFN: { city: "Santa Fe", isDomestic: false },
  SFO: { city: "San Francisco", isDomestic: false },
  SFT: { city: "Skelleftea", isDomestic: false },
  SGN: { city: "Ho Chi Minh City", isDomestic: false },
  SGU: { city: "St. George", isDomestic: false },
  SHA: { city: "Shanghai", isDomestic: false },
  SHE: { city: "Shenyang", isDomestic: false },
  SHS: { city: "Shashi", isDomestic: false },
  SJC: { city: "San Jose", isDomestic: false },
  SJJ: { city: "Sarajevo", isDomestic: false },
  SJW: { city: "Shijiazhuang", isDomestic: false },
  SKG: { city: "Thessaloniki", isDomestic: false },
  SKP: { city: "Skopje", isDomestic: false },
  SKZ: { city: "Sukkur", isDomestic: false },
  SLA: { city: "Salta", isDomestic: false },
  SLC: { city: "Salt Lake City", isDomestic: false },
  SLL: { city: "Salalah", isDomestic: false },
  SLP: { city: "San Luis Potosi", isDomestic: false },
  SMF: { city: "Sacramento", isDomestic: false },
  SMI: { city: "Samos", isDomestic: false },
  SNA: { city: "Santa Ana", isDomestic: false },
  SNN: { city: "Shannon", isDomestic: false },
  SOC: { city: "Solo", isDomestic: false },
  SOF: { city: "Sofia", isDomestic: false },
  SOQ: { city: "Sorong", isDomestic: false },
  SOU: { city: "Southampton", isDomestic: false },
  SPC: { city: "La Palma", isDomestic: false },
  SPD: { city: "Saidpur", isDomestic: false },
  SPK: { city: "Sapporo", isDomestic: false },
  SPU: { city: "Split", isDomestic: false },
  SQD: { city: "Sanqingshan", isDomestic: false },
  SQJ: { city: "Sanming", isDomestic: false },
  SRG: { city: "Semarang", isDomestic: false },
  SRZ: { city: "Santa Cruz", isDomestic: false },
  SSA: { city: "Salvador", isDomestic: false },
  SSG: { city: "Malabo", isDomestic: false },
  STL: { city: "St. Louis", isDomestic: false },
  STO: { city: "Stockholm", isDomestic: false },
  STR: { city: "Stuttgart", isDomestic: false },
  STV: { city: "Surat", isDomestic: false },
  SUB: { city: "Surabaya", isDomestic: false },
  SUF: { city: "Lamezia Terme", isDomestic: false },
  SUJ: { city: "Satu Mare", isDomestic: false },
  SUN: { city: "Sun Valley", isDomestic: false },
  SVD: { city: "Kingstown", isDomestic: false },
  SVG: { city: "Stavanger", isDomestic: false },
  SVO: { city: "Moscow", isDomestic: false },
  SVQ: { city: "Seville", isDomestic: false },
  SVX: { city: "Yekaterinburg", isDomestic: false },
  SWA: { city: "Shantou", isDomestic: false },
  SXB: { city: "Strasbourg", isDomestic: false },
  SXR: { city: "Srinagar", isDomestic: false },
  SXZ: { city: "Siirt", isDomestic: false },
  SYD: { city: "Sydney", isDomestic: false },
  SYM: { city: "Simao", isDomestic: false },
  SYX: { city: "Sanya", isDomestic: false },
  SZF: { city: "Samsun", isDomestic: false },
  SZG: { city: "Salzburg", isDomestic: false },
  SZX: { city: "Shenzhen", isDomestic: false },
  TAC: { city: "Tacloban", isDomestic: false },
  TAG: { city: "Tagbilaran", isDomestic: false },
  TAK: { city: "Takamatsu", isDomestic: false },
  TAM: { city: "Tampico", isDomestic: false },
  TAO: { city: "Qingdao", isDomestic: false },
  TAP: { city: "Tapachula", isDomestic: false },
  TBB: { city: "Tuy Hoa", isDomestic: false },
  TBS: { city: "Tbilisi", isDomestic: false },
  TCG: { city: "Tacheng", isDomestic: false },
  TCI: { city: "Tenerife", isDomestic: false },
  TCZ: { city: "Tengchong", isDomestic: false },
  TDX: { city: "Trat", isDomestic: false },
  TEN: { city: "Tongren", isDomestic: false },
  TFN: { city: "Tenerife", isDomestic: false },
  TFS: { city: "Tenerife", isDomestic: false },
  TFU: { city: "Chengdu", isDomestic: false },
  TGD: { city: "Podgorica", isDomestic: false },
  TGG: { city: "Kuala Terengganu", isDomestic: false },
  TGO: { city: "Tongliao", isDomestic: false },
  TGZ: { city: "Tuxtla Gutierrez", isDomestic: false },
  THD: { city: "Thanh Hoa", isDomestic: false },
  THR: { city: "Tehran", isDomestic: false },
  THS: { city: "Sukhothai", isDomestic: false },
  TIA: { city: "Tirana", isDomestic: false },
  TIF: { city: "Taif", isDomestic: false },
  TIJ: { city: "Tijuana", isDomestic: false },
  TIM: { city: "Timika", isDomestic: false },
  TIP: { city: "Tripoli", isDomestic: false },
  TIR: { city: "Tirupati", isDomestic: false },
  TIV: { city: "Tivat", isDomestic: false },
  TJK: { city: "Tokat", isDomestic: false },
  TKG: { city: "Bandar Lampung", isDomestic: false },
  TKU: { city: "Turku", isDomestic: false },
  TLL: { city: "Tallinn", isDomestic: false },
  TLS: { city: "Toulouse", isDomestic: false },
  TNA: { city: "Jinan", isDomestic: false },
  TNG: { city: "Tangier", isDomestic: false },
  TNH: { city: "Tonghua", isDomestic: false },
  TNJ: { city: "Tanjung Pinang", isDomestic: false },
  TNR: { city: "Antananarivo", isDomestic: false },
  TOJ: { city: "Madrid", isDomestic: false },
  TPA: { city: "Tampa", isDomestic: false },
  TPE: { city: "Taipei", isDomestic: false },
  TPQ: { city: "Tepic", isDomestic: false },
  TRC: { city: "Torreon", isDomestic: false },
  TRD: { city: "Trondheim", isDomestic: false },
  TRF: { city: "Oslo", isDomestic: false },
  TRI: { city: "Bristol", isDomestic: false },
  TRN: { city: "Turin", isDomestic: false },
  TRV: { city: "Thiruvananthapuram", isDomestic: false },
  TSA: { city: "Taipei", isDomestic: false },
  TSN: { city: "Tianjin", isDomestic: false },
  TSR: { city: "Timisoara", isDomestic: false },
  TTE: { city: "Ternate", isDomestic: false },
  TUC: { city: "Tucuman", isDomestic: false },
  TUI: { city: "Turaif", isDomestic: false },
  TUK: { city: "Turbat", isDomestic: false },
  TWF: { city: "Twin Falls", isDomestic: false },
  TXL: { city: "Berlin", isDomestic: false },
  TYN: { city: "Taiyuan", isDomestic: false },
  TYO: { city: "Tokyo", isDomestic: false },
  TYS: { city: "Knoxville", isDomestic: false },
  TZX: { city: "Trabzon", isDomestic: false },
  UDR: { city: "Udaipur", isDomestic: false },
  UFA: { city: "Ufa", isDomestic: false },
  UIH: { city: "Qui Nhon", isDomestic: false },
  UKB: { city: "Kobe", isDomestic: false },
  UME: { city: "Umea", isDomestic: false },
  UPG: { city: "Makassar", isDomestic: false },
  URC: { city: "Urumqi", isDomestic: false },
  USA: { city: "Concord", isDomestic: false },
  USH: { city: "Ushuaia", isDomestic: false },
  USM: { city: "Koh Samui", isDomestic: false },
  USN: { city: "Ulsan", isDomestic: false },
  UTN: { city: "Upington", isDomestic: false },
  UTP: { city: "Pattaya", isDomestic: false },
  UTT: { city: "Mthatha", isDomestic: false },
  UYN: { city: "Yulin", isDomestic: false },
  VAA: { city: "Vaasa", isDomestic: false },
  VAN: { city: "Van", isDomestic: false },
  VAR: { city: "Varna", isDomestic: false },
  VAS: { city: "Sivas", isDomestic: false },
  VBY: { city: "Visby", isDomestic: false },
  VCA: { city: "Can Tho", isDomestic: false },
  VCE: { city: "Venice", isDomestic: false },
  VCL: { city: "Chu Lai", isDomestic: false },
  VCS: { city: "Con Dao", isDomestic: false },
  VDE: { city: "Valverde", isDomestic: false },
  VDH: { city: "Dong Hoi", isDomestic: false },
  VDM: { city: "Viedma", isDomestic: false },
  VDO: { city: "Van Don", isDomestic: false },
  VER: { city: "Veracruz", isDomestic: false },
  VFA: { city: "Victoria Falls", isDomestic: false },
  VGA: { city: "Vijayawada", isDomestic: false },
  VGO: { city: "Vigo", isDomestic: false },
  VII: { city: "Vinh", isDomestic: false },
  VIL: { city: "Dakhla", isDomestic: false },
  VIT: { city: "Vitoria", isDomestic: false },
  VKG: { city: "Rach Gia", isDomestic: false },
  VLC: { city: "Valencia", isDomestic: false },
  VLD: { city: "Valdosta", isDomestic: false },
  VLL: { city: "Valladolid", isDomestic: false },
  VNO: { city: "Vilnius", isDomestic: false },
  VNS: { city: "Varanasi", isDomestic: false },
  VOZ: { city: "Voronezh", isDomestic: false },
  VRN: { city: "Verona", isDomestic: false },
  VSA: { city: "Villahermosa", isDomestic: false },
  VTE: { city: "Vientiane", isDomestic: false },
  VTZ: { city: "Visakhapatnam", isDomestic: false },
  VVI: { city: "Santa Cruz", isDomestic: false },
  VXO: { city: "Vaxjo", isDomestic: false },
  WAS: { city: "Washington", isDomestic: false },
  WAW: { city: "Warsaw", isDomestic: false },
  WDH: { city: "Windhoek", isDomestic: false },
  WDS: { city: "Shiyan", isDomestic: false },
  WEF: { city: "Weifang", isDomestic: false },
  WEH: { city: "Weihai", isDomestic: false },
  WHA: { city: "Wuhu", isDomestic: false },
  WMT: { city: "Zunyi", isDomestic: false },
  WNZ: { city: "Wenzhou", isDomestic: false },
  WUA: { city: "Wuhai", isDomestic: false },
  WUH: { city: "Wuhan", isDomestic: false },
  WUS: { city: "Wuyishan", isDomestic: false },
  WUT: { city: "Xinzhou", isDomestic: false },
  WUX: { city: "Wuxi", isDomestic: false },
  WXN: { city: "Wanxian", isDomestic: false },
  WYS: { city: "West Yellowstone", isDomestic: false },
  XAI: { city: "Xinyang", isDomestic: false },
  XIC: { city: "Xichang", isDomestic: false },
  XIL: { city: "Xilinhot", isDomestic: false },
  XIY: { city: "Xi'an", isDomestic: false },
  XMN: { city: "Xiamen", isDomestic: false },
  XNN: { city: "Xining", isDomestic: false },
  XRY: { city: "Jerez de la Frontera", isDomestic: false },
  XUZ: { city: "Xuzhou", isDomestic: false },
  XWA: { city: "Williston", isDomestic: false },
  YAM: { city: "Sault Ste. Marie", isDomestic: false },
  YBP: { city: "Yibin", isDomestic: false },
  YCU: { city: "Yuncheng", isDomestic: false },
  YDF: { city: "Deer Lake", isDomestic: false },
  YEG: { city: "Edmonton", isDomestic: false },
  YFC: { city: "Fredericton", isDomestic: false },
  YHZ: { city: "Halifax", isDomestic: false },
  YIA: { city: "Yogyakarta", isDomestic: false },
  YIH: { city: "Yichang", isDomestic: false },
  YIN: { city: "Yining", isDomestic: false },
  YIW: { city: "Yiwu", isDomestic: false },
  YKM: { city: "Yakima", isDomestic: false },
  YLW: { city: "Kelowna", isDomestic: false },
  YMM: { city: "Fort McMurray", isDomestic: false },
  YMQ: { city: "Montreal", isDomestic: false },
  YNJ: { city: "Yanji", isDomestic: false },
  YNT: { city: "Yantai", isDomestic: false },
  YNZ: { city: "Yancheng", isDomestic: false },
  YOW: { city: "Ottawa", isDomestic: false },
  YQB: { city: "Quebec City", isDomestic: false },
  YQG: { city: "Windsor", isDomestic: false },
  YQM: { city: "Moncton", isDomestic: false },
  YQR: { city: "Regina", isDomestic: false },
  YQT: { city: "Thunder Bay", isDomestic: false },
  YQY: { city: "Sydney", isDomestic: false },
  YSB: { city: "Sudbury", isDomestic: false },
  YSJ: { city: "Saint John", isDomestic: false },
  YTO: { city: "Toronto", isDomestic: false },
  YTS: { city: "Timmins", isDomestic: false },
  YTY: { city: "Yangzhou", isDomestic: false },
  YUL: { city: "Montreal", isDomestic: false },
  YUS: { city: "Yushu", isDomestic: false },
  YVA: { city: "Moroni", isDomestic: false },
  YVR: { city: "Vancouver", isDomestic: false },
  YWG: { city: "Winnipeg", isDomestic: false },
  YXE: { city: "Saskatoon", isDomestic: false },
  YXU: { city: "London", isDomestic: false },
  YYB: { city: "North Bay", isDomestic: false },
  YYC: { city: "Calgary", isDomestic: false },
  YYG: { city: "Charlottetown", isDomestic: false },
  YYJ: { city: "Victoria", isDomestic: false },
  YYT: { city: "St. John's", isDomestic: false },
  YZY: { city: "Zhangye", isDomestic: false },
  ZAD: { city: "Zadar", isDomestic: false },
  ZAG: { city: "Zagreb", isDomestic: false },
  ZAM: { city: "Zamboanga", isDomestic: false },
  ZAT: { city: "Zhaotong", isDomestic: false },
  ZAZ: { city: "Zaragoza", isDomestic: false },
  ZCL: { city: "Zacatecas", isDomestic: false },
  ZHA: { city: "Zhanjiang", isDomestic: false },
  ZHY: { city: "Zhongwei", isDomestic: false },
  ZIH: { city: "Ixtapa-Zihuatanejo", isDomestic: false },
  ZLO: { city: "Manzanillo", isDomestic: false },
  ZNZ: { city: "Zanzibar", isDomestic: false },
  ZQZ: { city: "Zhangjiakou", isDomestic: false },
  ZRH: { city: "Zurich", isDomestic: false },
  ZUH: { city: "Zhuhai", isDomestic: false },
  ZYI: { city: "Zunyi", isDomestic: false },
  ZYL: { city: "Sylhet", isDomestic: false },
};

export function getAirportCity(code: string): string {
  return AIRPORTS[code]?.city ?? code;
}

export function getAirportDisplay(code: string): string {
  const info = AIRPORTS[code];
  return info ? `${info.city} (${code})` : code;
}

export function isDomesticAirport(code: string): boolean {
  return AIRPORTS[code]?.isDomestic ?? false;
}

export function isDomesticTrip(
  legs: { departureAirport: string; arrivalAirport: string }[]
): boolean {
  return legs.every(
    (leg) =>
      isDomesticAirport(leg.departureAirport) &&
      isDomesticAirport(leg.arrivalAirport)
  );
}

export function getTripRouteType(
  legs: { departureAirport: string; arrivalAirport: string }[]
): "domestic" | "international" {
  return isDomesticTrip(legs) ? "domestic" : "international";
}

type AirportRow = { code: string; city: string; isDomestic: boolean };

let cachedAllAirports: AirportRow[] | null = null;
let cachedInternationalAirports: AirportRow[] | null = null;

/** All airports (cached; AIRPORTS is static at build time). */
export function getAllAirports(): AirportRow[] {
  if (!cachedAllAirports) {
    cachedAllAirports = Object.entries(AIRPORTS).map(([code, info]) => ({
      code,
      city: info.city,
      isDomestic: info.isDomestic,
    }));
  }
  return cachedAllAirports;
}

/** International airports only (cached). */
export function getInternationalAirports(): AirportRow[] {
  if (!cachedInternationalAirports) {
    cachedInternationalAirports = getAllAirports().filter((a) => !a.isDomestic);
  }
  return cachedInternationalAirports;
}

